_target_: lightning.pytorch.Trainer

accelerator: gpu
devices: auto  # Train on one A100
num_nodes: 1

log_every_n_steps: 10
min_epochs: ???
max_epochs: ???
num_sanity_val_steps: 2
overfit_batches: 0.0
precision: ???
val_check_interval: 1.0
detect_anomaly: false
