model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val/EV
  mode: max
  save_top_k: 1
  save_last: false
  save_weights_only: false
  verbose: true
  dirpath: ${ckpt_dir} 